version: '3.8'

services:
  ahk-db:
    image: postgres
    container_name: ahk-db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  ahk-pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: ahk-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - ahk-db

  ahk-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ahk-backend
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - ahk-db

networks:
  default:
    name: ahk-network
